version: '3.8'

services:
  app:
    build: .
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    command: npm start

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cooptmedb
      - POSTGRES_USER=cooptmeuser
      - POSTGRES_PASSWORD=cooptmepass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
