-- CreateEnum
CREATE TYPE "ProfileCategory" AS ENUM ('NEW', 'TECH', 'CREATIVE', 'MANAGEMENT', 'EDUCATION', 'HEALTHCARE', 'LEGAL', 'CONSULTING', 'ENTREPRENEURSHIP', 'INVESTING', 'SALES', 'MARKETING', 'PRODUCT', 'OPERATIONS', 'OTHER');

-- AlterTable
ALTER TABLE "Profile" ADD COLUMN     "category" "ProfileCategory" NOT NULL DEFAULT 'OTHER';
